-- Baseline schema. See docs/engineering/implementation-spec.md §4.
--
-- Conventions:
--   * Primary keys are UUIDv7, generated by the application (time-ordered, non-enumerable).
--   * Money is numeric(14,2); ratios and coefficients are numeric(6,4).
--   * Enums are varchar + CHECK. Native PG enum types are deliberately avoided — value lists
--     will change and altering a native enum inside a migration is painful.
--   * Timestamps are timestamptz stored in UTC. Europe/Istanbul is applied at presentation only.

-- ---------------------------------------------------------------------------
-- customer module
-- ---------------------------------------------------------------------------

CREATE TABLE customer (
  id                uuid PRIMARY KEY,
  phone             varchar(20) NOT NULL UNIQUE,
  email             varchar(255),
  display_name      varchar(128),
  customer_type     varchar(16) NOT NULL DEFAULT 'INDIVIDUAL',
  tax_number        varchar(20),
  default_district  varchar(32),
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  deleted_at        timestamptz,
  CONSTRAINT customer_type_check CHECK (customer_type IN ('INDIVIDUAL', 'BUSINESS'))
);

COMMENT ON TABLE customer IS
  'Owned by the customer module. A row is created only on successful OTP verification.';

-- ---------------------------------------------------------------------------
-- price book (all versioned; changing a coefficient must never alter existing quotes)
-- ---------------------------------------------------------------------------

CREATE TABLE price_book (
  id                      uuid PRIMARY KEY,
  version_code            varchar(32) NOT NULL UNIQUE,
  active                  boolean NOT NULL DEFAULT false,
  created_at              timestamptz NOT NULL DEFAULT now(),

  ceiling_height_m        numeric(4,2) NOT NULL DEFAULT 2.70,
  gross_to_net_ratio      numeric(5,4) NOT NULL DEFAULT 0.82,
  stage1_opening_ratio    numeric(5,4) NOT NULL DEFAULT 0.12,
  door_opening_m2         numeric(5,2) NOT NULL DEFAULT 1.90,
  window_opening_m2       numeric(5,2) NOT NULL DEFAULT 2.20,

  crew_size               integer NOT NULL DEFAULT 3,
  crew_hours_per_day      numeric(4,2) NOT NULL DEFAULT 8.00,
  crew_day_cost           numeric(14,2) NOT NULL,
  day_rounding_tolerance  numeric(4,2) NOT NULL DEFAULT 0.25,

  margin_ratio            numeric(5,4) NOT NULL DEFAULT 0.30,
  margin_alert_threshold  numeric(5,4) NOT NULL DEFAULT 0.20,
  survey_amount_factor    numeric(5,2) NOT NULL DEFAULT 2.00,

  labour_vat_rate         numeric(5,4) NOT NULL,
  material_vat_rate       numeric(5,4) NOT NULL,

  base_band_ratio         numeric(5,4) NOT NULL DEFAULT 0.12
);

CREATE UNIQUE INDEX price_book_single_active_idx ON price_book (active) WHERE active = true;

CREATE TABLE price_book_item (
  id              uuid PRIMARY KEY,
  price_book_id   uuid NOT NULL REFERENCES price_book(id) ON DELETE CASCADE,
  code            varchar(32) NOT NULL,
  unit            varchar(16) NOT NULL,
  labour_cost     numeric(14,2) NOT NULL,
  material_cost   numeric(14,2) NOT NULL,
  labour_minutes  numeric(8,2) NOT NULL,
  UNIQUE (price_book_id, code),
  CONSTRAINT price_book_item_unit_check CHECK (unit IN ('SQM', 'UNIT', 'ROOM', 'LUMP_SUM'))
);

CREATE TABLE price_modifier (
  id              uuid PRIMARY KEY,
  price_book_id   uuid NOT NULL REFERENCES price_book(id) ON DELETE CASCADE,
  code            varchar(32) NOT NULL,
  factor          numeric(6,4) NOT NULL,
  applies_to      varchar(16) NOT NULL,
  scope_items     jsonb,
  UNIQUE (price_book_id, code),
  CONSTRAINT price_modifier_applies_to_check CHECK (applies_to IN ('LABOUR', 'MATERIAL', 'BOTH'))
);

COMMENT ON COLUMN price_modifier.scope_items IS 'null means the modifier applies to every item';

CREATE TABLE room_type_config (
  id                uuid PRIMARY KEY,
  price_book_id     uuid NOT NULL REFERENCES price_book(id) ON DELETE CASCADE,
  room_type         varchar(24) NOT NULL,
  area_weight       numeric(5,2) NOT NULL,
  perimeter_factor  numeric(5,2) NOT NULL,
  paintable_ratio   numeric(5,4) NOT NULL,
  required_photos   jsonb NOT NULL,
  UNIQUE (price_book_id, room_type)
);

CREATE TABLE service_district (
  id                uuid PRIMARY KEY,
  price_book_id     uuid NOT NULL REFERENCES price_book(id) ON DELETE CASCADE,
  district_code     varchar(32) NOT NULL,
  display_name      varchar(64) NOT NULL,
  active            boolean NOT NULL DEFAULT true,
  district_factor   numeric(6,4) NOT NULL DEFAULT 1.0000,
  UNIQUE (price_book_id, district_code)
);

-- ---------------------------------------------------------------------------
-- quoting module
-- ---------------------------------------------------------------------------

CREATE TABLE quote_request (
  id                    uuid PRIMARY KEY,
  customer_id           uuid,
  status                varchar(32)  NOT NULL,
  created_at            timestamptz  NOT NULL DEFAULT now(),
  updated_at            timestamptz  NOT NULL DEFAULT now(),

  -- stage 1 inputs
  district_code         varchar(32),
  area_input            numeric(7,2),
  area_basis            varchar(8),
  net_area              numeric(7,2),
  layout                varchar(16),
  scope                 varchar(16),
  furnishing            varchar(16),
  doors_included        boolean,
  door_count            integer,
  door_colour_change    boolean,
  wall_condition        varchar(16),

  -- stage 1 output
  estimate_low          numeric(14,2),
  estimate_high         numeric(14,2),

  -- pre-verification contact (moved to customer on verify, then nulled)
  pending_phone         varchar(20),
  phone_verified_at     timestamptz,

  -- desktop → mobile handoff
  resume_token          varchar(64) UNIQUE,
  resume_token_expires  timestamptz,

  -- audit
  price_book_id         uuid REFERENCES price_book(id),
  recapture_count       integer NOT NULL DEFAULT 0,
  closed_at             timestamptz,
  close_outcome         varchar(16),

  CONSTRAINT quote_request_status_check CHECK (status IN (
    'DRAFT', 'PHOTOS_PENDING', 'ANALYZING', 'RECAPTURE_REQUIRED', 'PENDING_REVIEW',
    'SURVEY_REQUIRED', 'QUOTE_SENT', 'AWAITING_CONTACT', 'CLOSED')),
  CONSTRAINT quote_request_area_basis_check CHECK (area_basis IN ('GROSS', 'NET')),
  CONSTRAINT quote_request_scope_check CHECK (scope IN ('WHOLE_HOME', 'SELECTED_ROOMS')),
  CONSTRAINT quote_request_furnishing_check CHECK (furnishing IN ('EMPTY', 'PARTIAL', 'FURNISHED')),
  CONSTRAINT quote_request_wall_condition_check CHECK (wall_condition IN ('GOOD', 'MINOR', 'MAJOR', 'UNSURE')),
  CONSTRAINT quote_request_close_outcome_check CHECK (close_outcome IN ('WON', 'LOST', 'EXPIRED', 'CANCELLED'))
);

-- customer_id is a plain uuid with NO foreign key: it crosses a module boundary. Referential
-- integrity is the application's job, enforced in the customer module's API. A database-level FK
-- would let a future module quietly join across the boundary.
COMMENT ON COLUMN quote_request.customer_id IS
  'Cross-module reference to customer.id. Intentionally not a foreign key.';

CREATE INDEX quote_request_status_created_idx ON quote_request (status, created_at);
CREATE INDEX quote_request_customer_idx ON quote_request (customer_id) WHERE customer_id IS NOT NULL;

CREATE TABLE room (
  id                uuid PRIMARY KEY,
  quote_request_id  uuid NOT NULL REFERENCES quote_request(id) ON DELETE CASCADE,
  room_type         varchar(24) NOT NULL,
  label             varchar(64) NOT NULL,
  sort_order        integer NOT NULL,
  capture_complete  boolean NOT NULL DEFAULT false,
  UNIQUE (quote_request_id, sort_order)
);

COMMENT ON COLUMN room.label IS 'Customer-facing Turkish label, e.g. "Yatak odası 2"';

CREATE TABLE photo (
  id                 uuid PRIMARY KEY,
  room_id            uuid NOT NULL REFERENCES room(id) ON DELETE CASCADE,
  role               varchar(16) NOT NULL,
  storage_key        varchar(512) NOT NULL,
  uploaded_at        timestamptz,
  captured_at        timestamptz,
  width              integer,
  height             integer,
  byte_size          integer,
  quality_score      numeric(5,2),
  low_quality_flag   boolean NOT NULL DEFAULT false,
  delete_after       timestamptz,
  deleted_at         timestamptz,
  CONSTRAINT photo_role_check CHECK (role IN
    ('WALL_1', 'WALL_2', 'WALL_3', 'WALL_4', 'CEILING', 'DETAIL'))
);

COMMENT ON COLUMN photo.captured_at IS 'EXIF DateTimeOriginal, read client-side before EXIF is stripped';
COMMENT ON COLUMN photo.quality_score IS 'Client-side Laplacian variance';

CREATE INDEX photo_room_role_idx ON photo (room_id, role);
CREATE INDEX photo_delete_after_idx ON photo (delete_after) WHERE deleted_at IS NULL;

-- DETAIL photos are unbounded per room; every other role is unique per room.
CREATE UNIQUE INDEX photo_unique_role_idx ON photo (room_id, role) WHERE role <> 'DETAIL';

-- ---------------------------------------------------------------------------
-- analysis
-- ---------------------------------------------------------------------------

CREATE TABLE analysis_job (
  id            uuid PRIMARY KEY,
  room_id       uuid NOT NULL REFERENCES room(id) ON DELETE CASCADE,
  status        varchar(16) NOT NULL,
  attempts      integer NOT NULL DEFAULT 0,
  run_after     timestamptz NOT NULL DEFAULT now(),
  last_error    text,
  started_at    timestamptz,
  finished_at   timestamptz,
  CONSTRAINT analysis_job_status_check CHECK (status IN ('PENDING', 'RUNNING', 'DONE', 'FAILED'))
);

CREATE INDEX analysis_job_claim_idx ON analysis_job (status, run_after);

CREATE TABLE room_analysis (
  id                uuid PRIMARY KEY,
  room_id           uuid NOT NULL UNIQUE REFERENCES room(id) ON DELETE CASCADE,
  raw_response      jsonb NOT NULL,
  model_version     varchar(64) NOT NULL,
  prompt_version    varchar(32) NOT NULL,
  confidence        numeric(4,3) NOT NULL,
  furnishing        varchar(16),
  door_count        integer,
  window_count      integer,
  radiator_count    integer,
  cornice           boolean,
  downlight_count   integer,
  ceiling_staining  varchar(16),
  ceiling_filler    varchar(16),
  created_at        timestamptz NOT NULL DEFAULT now()
);

-- raw_response is the audit trail and lets prompt versions be compared. surface_finding is what
-- the pricing engine and calibration queries read — the engine must never parse JSON.
COMMENT ON COLUMN room_analysis.prompt_version IS
  'Mandatory. Without it, results from different prompts are incomparable and calibration data is worthless.';

CREATE TABLE surface_finding (
  id                  uuid PRIMARY KEY,
  room_analysis_id    uuid NOT NULL REFERENCES room_analysis(id) ON DELETE CASCADE,
  surface_id          varchar(16) NOT NULL,
  coating             varchar(16) NOT NULL,
  current_tone        varchar(16) NOT NULL,
  filler_ratio        varchar(16) NOT NULL,
  skim_coat_required  boolean NOT NULL,
  crack_level         varchar(16) NOT NULL,
  moisture            varchar(16) NOT NULL,
  wallpaper           boolean NOT NULL,
  confidence          numeric(4,3) NOT NULL,
  CONSTRAINT surface_finding_surface_check CHECK (surface_id IN
    ('WALL_1', 'WALL_2', 'WALL_3', 'WALL_4', 'ROOM_GENERAL')),
  CONSTRAINT surface_finding_coating_check CHECK (coating IN ('PAINTED', 'TILE', 'WOOD', 'BRICK')),
  CONSTRAINT surface_finding_tone_check CHECK (current_tone IN ('LIGHT', 'MEDIUM', 'DARK')),
  CONSTRAINT surface_finding_filler_check CHECK (filler_ratio IN ('NONE', 'LOW', 'MEDIUM', 'HIGH', 'FULL')),
  CONSTRAINT surface_finding_crack_check CHECK (crack_level IN ('NONE', 'HAIRLINE', 'VISIBLE', 'STRUCTURAL')),
  CONSTRAINT surface_finding_moisture_check CHECK (moisture IN ('NONE', 'STAIN', 'ACTIVE'))
);

CREATE INDEX surface_finding_analysis_idx ON surface_finding (room_analysis_id);

-- ---------------------------------------------------------------------------
-- quote
-- ---------------------------------------------------------------------------

CREATE TABLE quote (
  id                uuid PRIMARY KEY,
  quote_request_id  uuid NOT NULL REFERENCES quote_request(id) ON DELETE CASCADE,
  price_book_id     uuid NOT NULL REFERENCES price_book(id),
  revision          integer NOT NULL DEFAULT 1,
  status            varchar(24) NOT NULL,

  total_cost        numeric(14,2) NOT NULL,
  subtotal          numeric(14,2) NOT NULL,
  vat_amount        numeric(14,2) NOT NULL,
  total             numeric(14,2) NOT NULL,
  band_low          numeric(14,2) NOT NULL,
  band_high         numeric(14,2) NOT NULL,
  margin_ratio      numeric(5,4) NOT NULL,
  minimum_applied   boolean NOT NULL DEFAULT false,

  estimated_days    integer NOT NULL,
  total_wall_sqm    numeric(8,2) NOT NULL,
  total_ceiling_sqm numeric(8,2) NOT NULL,

  valid_until       timestamptz,
  sent_at           timestamptz,
  created_by        varchar(16) NOT NULL,
  created_at        timestamptz NOT NULL DEFAULT now(),
  UNIQUE (quote_request_id, revision),
  CONSTRAINT quote_status_check CHECK (status IN
    ('DRAFT', 'SENT', 'ACCEPTED', 'EXPIRED', 'SUPERSEDED')),
  CONSTRAINT quote_created_by_check CHECK (created_by IN ('SYSTEM', 'OPERATOR'))
);

COMMENT ON COLUMN quote.total_cost IS 'Internal only. Must never reach a customer-facing DTO.';

CREATE TABLE quote_line_item (
  id                uuid PRIMARY KEY,
  quote_id          uuid NOT NULL REFERENCES quote(id) ON DELETE CASCADE,
  item_code         varchar(32) NOT NULL,
  quantity          numeric(10,2) NOT NULL,
  unit              varchar(16) NOT NULL,
  labour_cost       numeric(14,2) NOT NULL,
  material_cost     numeric(14,2) NOT NULL,
  applied_modifiers jsonb NOT NULL,
  line_total        numeric(14,2) NOT NULL,
  labour_minutes    numeric(10,2) NOT NULL,
  sort_order        integer NOT NULL
);

COMMENT ON COLUMN quote_line_item.applied_modifiers IS
  'e.g. [{"code":"FURNISHED","factor":1.25}] — answers "why does this line carry a 1.5 factor" six months later';

CREATE INDEX quote_line_item_quote_idx ON quote_line_item (quote_id);

CREATE TABLE quote_adjustment (
  id            uuid PRIMARY KEY,
  quote_id      uuid NOT NULL REFERENCES quote(id) ON DELETE CASCADE,
  item_code     varchar(32) NOT NULL,
  finding_path  varchar(128),
  old_quantity  numeric(10,2),
  new_quantity  numeric(10,2),
  operator_id   uuid,
  created_at    timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE quote_adjustment IS
  'The calibration dataset. Structured, not free text. finding_path looks like "LIVING_ROOM.WALL_3.skim_coat_required".';

CREATE INDEX quote_adjustment_quote_idx ON quote_adjustment (quote_id);

-- ---------------------------------------------------------------------------
-- operations
-- ---------------------------------------------------------------------------

CREATE TABLE callback_task (
  id                uuid PRIMARY KEY,
  quote_request_id  uuid NOT NULL REFERENCES quote_request(id) ON DELETE CASCADE,
  reason            varchar(16) NOT NULL,
  preferred_slot    varchar(16),
  status            varchar(24) NOT NULL,
  overdue_flagged   boolean NOT NULL DEFAULT false,
  notes             text,
  created_at        timestamptz NOT NULL DEFAULT now(),
  resolved_at       timestamptz,
  CONSTRAINT callback_task_reason_check CHECK (reason IN ('ACCEPTED', 'SURVEY', 'QUESTION')),
  CONSTRAINT callback_task_slot_check CHECK (preferred_slot IN ('MORNING', 'AFTERNOON', 'EVENING')),
  CONSTRAINT callback_task_status_check CHECK (status IN
    ('OPEN', 'WON', 'THINKING', 'UNREACHABLE', 'LOST'))
);

CREATE INDEX callback_task_status_created_idx ON callback_task (status, created_at);

CREATE TABLE job_outcome (
  id                uuid PRIMARY KEY,
  quote_request_id  uuid NOT NULL UNIQUE REFERENCES quote_request(id),
  actual_total      numeric(14,2) NOT NULL,
  actual_days       integer NOT NULL,
  actual_cost       numeric(14,2),
  notes             text,
  recorded_at       timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE job_outcome IS 'Stage 8 calibration input: estimate versus reality.';

CREATE TABLE consent (
  id                uuid PRIMARY KEY,
  quote_request_id  uuid NOT NULL REFERENCES quote_request(id) ON DELETE CASCADE,
  consent_type      varchar(32) NOT NULL,
  granted           boolean NOT NULL,
  text_version      varchar(32) NOT NULL,
  ip_address        inet,
  created_at        timestamptz NOT NULL DEFAULT now(),
  revoked_at        timestamptz,
  CONSTRAINT consent_type_check CHECK (consent_type IN ('PROCESSING', 'RETENTION_FOR_IMPROVEMENT'))
);

COMMENT ON COLUMN consent.text_version IS
  'Which version of the notice this grant referred to. Revocation triggers immediate deletion.';

CREATE TABLE notification (
  id                uuid PRIMARY KEY,
  quote_request_id  uuid REFERENCES quote_request(id) ON DELETE CASCADE,
  channel           varchar(16) NOT NULL,
  template_code     varchar(48) NOT NULL,
  recipient         varchar(255) NOT NULL,
  status            varchar(16) NOT NULL,
  provider_ref      varchar(128),
  sent_at           timestamptz,
  created_at        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT notification_channel_check CHECK (channel IN ('SMS', 'EMAIL')),
  CONSTRAINT notification_status_check CHECK (status IN ('QUEUED', 'SENT', 'FAILED'))
);

CREATE INDEX notification_status_idx ON notification (status, created_at);

CREATE TABLE rate_limit_counter (
  id            uuid PRIMARY KEY,
  scope_key     varchar(128) NOT NULL,
  bucket        varchar(32) NOT NULL,
  window_start  timestamptz NOT NULL,
  count         integer NOT NULL DEFAULT 0,
  UNIQUE (scope_key, bucket, window_start),
  CONSTRAINT rate_limit_bucket_check CHECK (bucket IN ('ANALYSIS', 'OTP', 'WAITLIST'))
);

COMMENT ON COLUMN rate_limit_counter.scope_key IS 'e.g. "phone:+9053..." or "ip:1.2.3.4"';

-- ---------------------------------------------------------------------------
-- outbox (§2.4)
--
-- Domain events are published in-process with @TransactionalEventListener(AFTER_COMMIT), which is
-- sufficient at this scale. A row lands here only when a subscriber's failure must not be silently
-- lost — currently QuoteSent (the SMS; a lost SMS is a lost sale) and QuoteClosed (photo deletion
-- scheduling; losing it leaves customer photographs on disk past their retention window).
--
-- event_type is the event's own stable TYPE constant, not a class name: renaming a class must not
-- orphan rows already sitting here.
-- ---------------------------------------------------------------------------

CREATE TABLE outbox (
  id            uuid PRIMARY KEY,
  event_type    varchar(64) NOT NULL,
  aggregate_id  uuid NOT NULL,
  payload       jsonb NOT NULL,
  occurred_at   timestamptz NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),
  published_at  timestamptz,
  attempts      integer NOT NULL DEFAULT 0,
  run_after     timestamptz NOT NULL DEFAULT now(),
  last_error    text
);

-- Claimed the same way as analysis_job: FOR UPDATE SKIP LOCKED, so it stays correct across
-- instances without a broker.
CREATE INDEX outbox_unpublished_idx ON outbox (run_after) WHERE published_at IS NULL;
CREATE INDEX outbox_aggregate_idx ON outbox (aggregate_id);

-- ---------------------------------------------------------------------------
-- service area waitlist
--
-- A visitor whose district is not served is eliminated by the very first question of stage 1
-- (is-akis-sureci.md §7 decision 1). Rather than losing them, they may ask to be told when the
-- district opens (§8). This is the only place in the system that holds a phone number belonging to
-- someone who never became a customer, so it is deliberately separate from `customer`: a customer
-- row is created only on OTP verification, and these visitors never verify.
--
-- The unique constraint carries the actual requirement. Signing up twice must not create a second
-- row, because opening the district later would then text the same person twice — which is what
-- turns a goodwill list into a complaint.
-- ---------------------------------------------------------------------------

CREATE TABLE service_area_waitlist (
  id                    uuid PRIMARY KEY,
  district_code         varchar(32) NOT NULL,
  phone                 varchar(20) NOT NULL,
  quote_request_id      uuid REFERENCES quote_request(id) ON DELETE SET NULL,
  consent_text_version  varchar(32) NOT NULL,
  created_at            timestamptz NOT NULL DEFAULT now(),
  notified_at           timestamptz,
  UNIQUE (district_code, phone)
);

-- district_code is intentionally not a foreign key into service_district: the whole point is that
-- the district is *not* in that table yet.
COMMENT ON COLUMN service_area_waitlist.district_code IS
  'A district outside the served area. Not a foreign key — service_district holds only served ones.';

COMMENT ON COLUMN service_area_waitlist.consent_text_version IS
  'Which notice this person agreed to. §16 puts the commercial-versus-informational classification of the eventual message with legal counsel.';

CREATE INDEX service_area_waitlist_pending_idx
  ON service_area_waitlist (district_code) WHERE notified_at IS NULL;

CREATE TABLE deletion_request (
  id                uuid PRIMARY KEY,
  quote_request_id  uuid NOT NULL REFERENCES quote_request(id),
  requested_at      timestamptz NOT NULL DEFAULT now(),
  approved_at       timestamptz,
  executed_at       timestamptz,
  operator_id       uuid
);

CREATE INDEX deletion_request_pending_idx ON deletion_request (requested_at) WHERE executed_at IS NULL;
