/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/op/price-books/{id}/items/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateItem"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/op/price-calculations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["calculate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/op/price-books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/op/price-books/{id}/bulk-increase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["bulkIncrease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/op/price-books/{id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["activate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/op/price-books/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UpdateItemRequest: {
            materialCost: number;
            labourMinutes: number;
        };
        PriceBookItemResponse: {
            /** @enum {string} */
            code: "WALL_PAINT" | "CEILING_PAINT" | "PATCH_FILLING" | "SKIM_COAT" | "PRIMER" | "STAIN_BLOCK_PRIMER" | "WALLPAPER_STRIPPING" | "DOOR_PAINT" | "TRIM_PAINT" | "RADIATOR_PAINT" | "DOWNLIGHT_CUTTING" | "CORNICE_CUTTING" | "MASKING" | "MOBILIZATION";
            /** @enum {string} */
            unit: "SQM" | "UNIT" | "ROOM" | "LUMP_SUM";
            labourCost: number;
            materialCost: number;
            labourMinutes: number;
        };
        ProblemDetail: {
            /** Format: uri */
            type?: string;
            title?: string;
            /** Format: int32 */
            status?: number;
            detail?: string;
            /** Format: uri */
            instance?: string;
            properties?: {
                [key: string]: unknown;
            };
        };
        CalculateQuoteRequest: {
            districtCode: string;
            area: number;
            /** @enum {string} */
            areaBasis: "GROSS" | "NET";
            /** @enum {string} */
            layout: "STUDIO" | "ONE_PLUS_ONE" | "TWO_PLUS_ONE" | "THREE_PLUS_ONE" | "FOUR_PLUS_ONE" | "FIVE_PLUS_ONE";
            /** @enum {string} */
            scope: "WHOLE_HOME" | "SELECTED_ROOMS";
            selectedRooms?: ("LIVING_ROOM" | "MASTER_BEDROOM" | "BEDROOM" | "STUDY" | "KITCHEN" | "BATHROOM" | "HALLWAY" | "BALCONY")[];
            /** @enum {string} */
            wallCondition: "GOOD" | "MINOR" | "MAJOR" | "UNSURE";
            /** @enum {string} */
            furnishing: "EMPTY" | "PARTIAL" | "FURNISHED";
            /** Format: int32 */
            doorCount?: number;
            doorColourChange?: boolean;
            doorCountEstimated?: boolean;
            hasElevator?: boolean;
            rush?: boolean;
        };
        CalculatedRoomResponse: {
            /** @enum {string} */
            type: "LIVING_ROOM" | "MASTER_BEDROOM" | "BEDROOM" | "STUDY" | "KITCHEN" | "BATHROOM" | "HALLWAY" | "BALCONY";
            label: string;
            /** Format: int32 */
            requiredPhotos: number;
        };
        QuoteCalculationResponse: {
            priceBookVersion: string;
            netArea: number;
            areaWasGross: boolean;
            rooms: components["schemas"]["CalculatedRoomResponse"][];
            /** Format: int32 */
            photoCount: number;
            lines: components["schemas"]["QuoteLineResponse"][];
            totalMinutes: number;
            /** Format: int32 */
            billableDays: number;
            minimumCost: number;
            minimumBinding: boolean;
            totalCost: number;
            subtotalExVat: number;
            vatAmount: number;
            total: number;
            labour: components["schemas"]["QuotePortionResponse"];
            material: components["schemas"]["QuotePortionResponse"];
            bandRatio: number;
            bandLow: number;
            bandHigh: number;
        };
        QuoteLineResponse: {
            /** @enum {string} */
            code: "WALL_PAINT" | "CEILING_PAINT" | "PATCH_FILLING" | "SKIM_COAT" | "PRIMER" | "STAIN_BLOCK_PRIMER" | "WALLPAPER_STRIPPING" | "DOOR_PAINT" | "TRIM_PAINT" | "RADIATOR_PAINT" | "DOWNLIGHT_CUTTING" | "CORNICE_CUTTING" | "MASKING" | "MOBILIZATION";
            /** @enum {string} */
            unit: "SQM" | "UNIT" | "ROOM" | "LUMP_SUM";
            quantity: number;
            labourCost: number;
            materialCost: number;
            lineTotal: number;
        };
        QuotePortionResponse: {
            totalCost: number;
            subtotalExVat: number;
            vatAmount: number;
            total: number;
        };
        CreatePriceBookVersionRequest: {
            /** Format: uuid */
            sourceId: string;
            versionCode: string;
        };
        PriceBookSummaryResponse: {
            /** Format: uuid */
            id: string;
            versionCode: string;
            active: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        BulkIncreaseRequest: {
            /** @enum {string} */
            target: "LABOUR" | "MATERIAL" | "ALL";
            percent: number;
        };
        Coefficients: {
            ceilingHeightM: number;
            grossToNetRatio: number;
            stage1OpeningRatio: number;
            /** Format: int32 */
            crewSize: number;
            crewHoursPerDay: number;
            crewDayCost: number;
            marginRatio: number;
            marginAlertThreshold: number;
            labourVatRate: number;
            materialVatRate: number;
            baseBandRatio: number;
        };
        PriceBookDetailResponse: {
            /** Format: uuid */
            id: string;
            versionCode: string;
            active: boolean;
            editable: boolean;
            /** Format: date-time */
            createdAt: string;
            coefficients: components["schemas"]["Coefficients"];
            items: components["schemas"]["PriceBookItemResponse"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    updateItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                code: "WALL_PAINT" | "CEILING_PAINT" | "PATCH_FILLING" | "SKIM_COAT" | "PRIMER" | "STAIN_BLOCK_PRIMER" | "WALLPAPER_STRIPPING" | "DOOR_PAINT" | "TRIM_PAINT" | "RADIATOR_PAINT" | "DOWNLIGHT_CUTTING" | "CORNICE_CUTTING" | "MASKING" | "MOBILIZATION";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateItemRequest"];
            };
        };
        responses: {
            /** @description The item as it now stands */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PriceBookItemResponse"];
                };
            };
            /** @description A figure the price list cannot hold */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No version with that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description The version has priced quotes; copy it and edit the copy */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    calculate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalculateQuoteRequest"];
            };
        };
        responses: {
            /** @description The price and everything assumed to reach it */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QuoteCalculationResponse"];
                };
            };
            /** @description A job the price book cannot price */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PriceBookSummaryResponse"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePriceBookVersionRequest"];
            };
        };
        responses: {
            /** @description The new version, inactive */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PriceBookSummaryResponse"];
                };
            };
            /** @description No source version with that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description That version code is taken */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    bulkIncrease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkIncreaseRequest"];
            };
        };
        responses: {
            /** @description The raised version, inactive */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PriceBookSummaryResponse"];
                };
            };
            /** @description A percent nobody meant to type */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No version with that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    activate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The version, now live */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PriceBookSummaryResponse"];
                };
            };
            /** @description No version with that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The version, its items and its coefficients */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PriceBookDetailResponse"];
                };
            };
            /** @description No version with that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
}
